import type { IconType } from "react-icons";
import { FaAws } from "react-icons/fa6";
import { RiOpenaiFill } from "react-icons/ri";
import {
  SiAirtable,
  SiCloudflare,
  SiCplusplus,
  SiDocker,
  SiDotnet,
  SiDrizzle,
  SiElectron,
  SiExpo,
  SiExpress,
  SiFastapi,
  SiFfmpeg,
  SiFirebase,
  SiFlask,
  SiGodotengine,
  SiGooglegemini,
  SiGraphql,
  SiHono,
  SiHuggingface,
  SiJavascript,
  SiLangchain,
  SiLaravel,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiNumpy,
  SiOllama,
  SiOpencv,
  SiPandas,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiRailway,
  SiReact,
  SiRedux,
  SiResend,
  SiScikitlearn,
  SiSqlite,
  SiStripe,
  SiSupabase,
  SiTailwindcss,
  SiTensorflow,
  SiTrpc,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWebrtc,
  SiZapier,
} from "react-icons/si";
import { TbBrandTwilio } from "react-icons/tb";

const icons: Record<string, IconType> = {
  "next.js": SiNextdotjs,
  react: SiReact,
  "react native": SiReact,
  typescript: SiTypescript,
  javascript: SiJavascript,
  "node.js": SiNodedotjs,
  python: SiPython,
  fastapi: SiFastapi,
  flask: SiFlask,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  sqlite: SiSqlite,
  supabase: SiSupabase,
  "supabase storage": SiSupabase,
  docker: SiDocker,
  "tailwind css": SiTailwindcss,
  openai: RiOpenaiFill,
  stripe: SiStripe,
  twilio: TbBrandTwilio,
  vercel: SiVercel,
  aws: FaAws,
  "aws s3": FaAws,
  pytorch: SiPytorch,
  opencv: SiOpencv,
  tensorflow: SiTensorflow,
  "scikit-learn": SiScikitlearn,
  pandas: SiPandas,
  numpy: SiNumpy,
  laravel: SiLaravel,
  php: SiPhp,
  graphql: SiGraphql,
  trpc: SiTrpc,
  "drizzle orm": SiDrizzle,
  redux: SiRedux,
  express: SiExpress,
  nginx: SiNginx,
  firebase: SiFirebase,
  gemini: SiGooglegemini,
  "gemini api": SiGooglegemini,
  hono: SiHono,
  langchain: SiLangchain,
  "hugging face": SiHuggingface,
  ollama: SiOllama,
  expo: SiExpo,
  electron: SiElectron,
  vite: SiVite,
  railway: SiRailway,
  resend: SiResend,
  webrtc: SiWebrtc,
  ffmpeg: SiFfmpeg,
  "cloudflare r2": SiCloudflare,
  godot: SiGodotengine,
  "c++": SiCplusplus,
  "c++17": SiCplusplus,
  ".net": SiDotnet,
  airtable: SiAirtable,
  zapier: SiZapier,
};

interface TechIconProps {
  name: string;
  className?: string;
}

export function TechIcon({ name, className }: TechIconProps) {
  const Icon = icons[name.toLowerCase()];
  return Icon ? <Icon className={className} aria-hidden /> : null;
}
